// Every piece of code in this file will be available to every web page,
// Code in any other files (pages) which in our case in only one (yet)
// i.e page.js will be rendered in {children} between main tag

import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/components/misc/Provider";
import { Toaster } from "react-hot-toast"; // Import Toaster in layout, so it will be avalible to every web page.

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CHATGPT", // Set title for web page
  description: "Generated by create next app", // Set meta description for web page
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* // Toaster to show success and error message */}
      <Toaster />
      {/* // This Provider has wrap the application, in order to cache the data received from openai apis. */}
      <Provider>
        <body className={inter.className}>
          <main className="bg-gray-50 dark:bg-[#09090b] min-h-screen">
            {children}
          </main>
        </body>
      </Provider>
    </html>
  );
}
