// This page style the responses generated by chat gpt.
// memo from react memorize the styles and prevent the re-rendering of the styles.
// This improve the performance of the app.

import { memo } from 'react'
import ReactMarkdown from 'react-markdown'

export const MemoizedReactMarkdown = memo(
  ReactMarkdown,
  (prevProps, nextProps) =>
    prevProps.children === nextProps.children &&
    prevProps.className === nextProps.className
)
