// This is APi route for sending request to openAI serer to fetch responses from Chatgpt model.

import { OpenAIStream } from "@/lib/openai-stream"; // import the OpenAIStream function from the openai-stream.js file in lib folder

export async function POST(req) {
  const { messages } = await req.json(); // get the messages from the request body

  // The messages are mapped to the format that is required by the OpenAI API
  // The Role User contains chats/prompts entered by user
  // The Role System contains responses sent by chatgpt

  const outboundMessages = messages.map((message) => {
    return {
      role: message.isUserMessage ? "user" : "system",
      content: message.text,
    };
  });

  // The payload is the data that will be sent to the OpenAI API
  const payload = {
    model: "gpt-3.5-turbo",
    messages: outboundMessages,
    temperature: 0.4,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
    max_tokens: 150,
    stream: true,
    n: 1,
  };

  const stream = await OpenAIStream(payload); // call the OpenAIStream function with the payload (it will return a stream which will create typing animation when response will be generated by AI.)

  return new Response(stream);
}
